[toolchain]
anchor_version = "0.28.0"
solana_version = "1.18.4"

[features]
resolution = true
skip-lint = false

[programs.devnet]
fee_rewards = "5jeZr9rczv1NrQdsrNrHAnZAzZht6KRDTCvEWoWhuLna"
holder_distribution = "3GuaNdYEfhBBd69ejiow6Xo6HeBoFXtzD4txED5bMTxX"
lp_custody = "423GhdzXo7gogEHQz5Np2FfmF28P3B3acHufnU8WcHey"
project_status_tracker = "AKmu1fAHBfL25EdruRLrNxRARwk66ixzHXyfEQAKieqV"
daily_game_vault = "5DhpMM7Qbi7HK8H2LJJjvBqLCmasQVwqirexo61UpikF"
category_tracker = "FWVc9huqjX9XbPJ8BZ1KFmz572pyqXRtsF5gFRVTEx97"
apeout_swap = "GeTSVKTigSuwtBtVDPKhcxGX4TXizJQxtjwQeCYPaJ9z"
token_launcher = "Aqtnv6qAEE5PzbfPBL3bS4JyjkPFuiZb1YTW8pLZRRdw"

[programs.mainnet]
fee_rewards = "5jeZr9rczv1NrQdsrNrHAnZAzZht6KRDTCvEWoWhuLna"
holder_distribution = "3GuaNdYEfhBBd69ejiow6Xo6HeBoFXtzD4txED5bMTxX"
lp_custody = "423GhdzXo7gogEHQz5Np2FfmF28P3B3acHufnU8WcHey"
project_status_tracker = "AKmu1fAHBfL25EdruRLrNxRARwk66ixzHXyfEQAKieqV"
daily_game_vault = "5DhpMM7Qbi7HK8H2LJJjvBqLCmasQVwqirexo61UpikF"
category_tracker = "FWVc9huqjX9XbPJ8BZ1KFmz572pyqXRtsF5gFRVTEx97"
apeout_swap = "GeTSVKTigSuwtBtVDPKhcxGX4TXizJQxtjwQeCYPaJ9z"
token_launcher = "Aqtnv6qAEE5PzbfPBL3bS4JyjkPFuiZb1YTW8pLZRRdw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
    "programs/fee-rewards", 
    "programs/holder-distribution", 
    "programs/lp-custody", 
    "programs/project-status-tracker", 
    "programs/daily-game-vault",
    "programs/category-tracker",
    "programs/apeout-swap",
    "programs/token-launcher"
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.devnet.solana.com"
commitment = "processed"
ledger = ".anchor/test-ledger"
bind_address = "0.0.0.0"

[build]
exclude = ["node_modules"]