[package]
name = "holder-distribution"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "holder_distribution"

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
